//! HR3.2.0 Step 3 oracle-follow-up regression test: pin the
//! back-compat surface for `worker = rpc(T) + async_worker = true`.
//!
//! Before the Step 3 oracle round-2 fix, the macro would key the
//! `async_worker` validation off the *post-translation* effective
//! scope. With `scope = Hosted, worker = rpc(T)` translating to
//! `Scope::HostedRpc` internally, the validation then ran with
//! "effective_scope != Hosted" and hard-errored — even though the
//! user wrote exactly `scope = Hosted`.
//!
//! After the fix, the validation keys off the user-*declared* scope,
//! so this same combination is accepted at the macro level and only
//! produces the worker-view-neutral deprecation warning at the
//! generated `register_dep_…` site.
//!
//! This fixture exists purely to keep that path compiled, accepted,
//! and end-to-end wired. The `#[allow(deprecated)]` wrappers keep CI
//! quiet about the warning while still exercising the path; the
//! deprecation note itself is verified empirically (removing the
//! flag makes the warning vanish).

#[cfg(test)]
#[allow(deprecated)]
mod tests {
    use std::sync::Mutex;
    use test_r::core::{HostedRpcChannel, HostedRpcDep};
    use test_r::{hosted_rpc, test, test_dep};

    /// Minimal trait that the `#[hosted_rpc]` macro turns into a
    /// `LegacyCounterStub` worker-side stub plus dispatcher.
    #[hosted_rpc]
    pub trait LegacyCounter {
        fn next(&self) -> u64;
    }

    /// Parent-held owner state. The new `worker = rpc(LegacyCounter)`
    /// sugar derives the stub path as `LegacyCounterStub`, and the
    /// macro wires both ends of the RPC.
    pub struct LegacyCounterOwner {
        counter: Mutex<u64>,
    }

    impl LegacyCounterOwner {
        fn new() -> Self {
            Self {
                counter: Mutex::new(0),
            }
        }
    }

    impl LegacyCounter for LegacyCounterOwner {
        fn next(&self) -> u64 {
            let mut g = self.counter.lock().unwrap();
            *g += 1;
            *g
        }
    }

    /// Mandatory glue for the HostedRpc translation path. The
    /// `worker = rpc(LegacyCounter)` sugar only derives the stub type
    /// name; the owner still has to opt into the RPC plumbing via
    /// `HostedRpcDep` (`type Stub = …`, `dispatch(...)`,
    /// `build_stub(...)`). The dispatcher helper is generated by the
    /// `#[hosted_rpc]` macro.
    impl HostedRpcDep for LegacyCounterOwner {
        type Stub = LegacyCounterStub;

        fn dispatch(&mut self, method_idx: u32, args: &[u8]) -> Result<Vec<u8>, String> {
            LegacyCounterDispatch::dispatch_legacy_counter(self, method_idx, args)
        }

        fn build_stub(channel: HostedRpcChannel) -> Self::Stub {
            LegacyCounterStub::new(channel)
        }
    }

    /// **The whole point of this fixture.** Before the Step 3 round-2
    /// oracle fix, the `async_worker` validation would hard-error
    /// here because the post-translation effective scope is
    /// `Scope::HostedRpc`. After the fix, validation keys off the
    /// declared scope (`Hosted`), so this combination is accepted
    /// and only fires the deprecation warning (which the module-level
    /// `#[allow(deprecated)]` suppresses).
    #[test_dep(scope = Hosted, worker = rpc(LegacyCounter), async_worker)]
    fn legacy_counter_owner() -> LegacyCounterOwner {
        LegacyCounterOwner::new()
    }

    /// End-to-end smoke test: the dep is wired correctly through the
    /// HostedRpc translation, the worker stub round-trips a call to
    /// the owner, and the result is the expected monotonic id.
    #[test]
    async fn legacy_combination_round_trips_a_call(stub: &LegacyCounterStub) {
        let v = stub.next();
        assert!(v >= 1, "ids start at 1, got {v}");
    }
}
